const usStateFlags: { [key: string]: string } = {
  Alabama: '/flags/alabama.png',
  Alaska: '/flags/alaska.png',
  Arizona: '/flags/arizona.png',
  Utah: '/flags/utah.png',
  Mississippi: '/flags/mississippi.png',
  Ohio: '/flags/ohio.png',
  Kentucky: '/flags/kentucky.png',
  Arkansas: '/flags/arkansas.png',
  Montana: '/flags/montana.png',
  California: '/flags/california.png',
  Oregon: '/flags/oregon.png',
  Indiana: '/flags/indiana.png',
  Hawaii: '/flags/hawaii.png',
  Louisiana: '/flags/louisiana.png',
  Nevada: '/flags/nevada.png',
  Missouri: '/flags/missouri.png',
  Texas: '/flags/texas.png',
  Illinois: '/flags/illinois.png',
  Georgia: '/flags/georgia.png',
  'South Carolina': '/flags/southcarolina.png',
  'North Carolina': '/flags/northcarolina.png',
  Oklahoma: '/flags/oklahoma.png',
  'New York': '/flags/newyork.png',
  Iowa: '/flags/iowa.png',
  Michigan: '/flags/michigan.png',
  Minnesota: '/flags/minnesota.png',
  Wyoming: '/flags/wyoming.png',
  Wisconsin: '/flags/wisconsin.png',
  Tennessee: '/flags/tennessee.png',
  Virginia: '/flags/virginia.png',
  'New Jersey': '/flags/newjersey.png',
  Pennsylvania: '/flags/pennsylvania.png',
  Maryland: '/flags/maryland.png',
  Delaware: '/flags/delaware.png',
  Kansas: '/flags/kansas.png',
  Colorado: '/flags/colorado.png',
  Nebraska: '/flags/nebraska.png',
  'South Dakota': '/flags/southdakota.png',
  Florida: '/flags/florida.png',
  Massachusetts: '/flags/massachusetts.png',
  'New Hampshire': '/flags/newhampshire.png',
  Vermont: '/flags/vermont.png',
  Connecticut: '/flags/connecticut.png',
  'Rhode Island': '/flags/rhodeisland.png',
  Maine: '/flags/maine.png',
  'New Mexico': '/flags/newmexico.png',
  Idaho: '/flags/idaho.png',
  'North Dakota': '/flags/northdakota.png',
  Washington: '/flags/washington.png',
  'West Virginia': '/flags/westvirginia.png',
  'District of Columbia': '/flags/washington.png',
  Guam: '/flags/guam.png',
  'Puerto Rico': '/flags/puertorico.png',
  'Navajo Nation': '/flags/navajonation.png',
  'United States Virgin Islands': '/flags/unitedstatesvirginisland.png',
  'Northern Mariana Islands': '/flags/northernmarianaislands.png',
  'American Samoa': '/flags/americansamoa.png',
};

export default usStateFlags;
